%% save_all_figures.m
% PURPOSE:
%   Generates, visualizes, and exports all required figures and data
%   for the Speech Enhancement CEP project. Ensures reproducible
%   results and standardized figure outputs for report submission.

% INPUTS:
%   - data struct (must be generated by running):
%       1. loadaudios_1.m       → loads clean and noisy signals
%       2. SNR_PSEQ_6.m         → computes baseline metrics
%       3. Filter_applied_7.m   → generates enhanced signals
%
%   Required fields in data:
%       data(i).clean
%       data(i).noisy
%       data(i).enhanced
%       data(i).Fs
%       data(i).segSNR_baseline
%       data(i).segSNR_enhanced
%       data(i).mse

% OUTPUTS:
%   - figures/ directory containing:
%       Fig1 : Filter Frequency Response (.fig, .png)
%       Fig2 : Group Delay
%       Fig3 : Time-Domain Waveforms (Clean/Noisy/Enhanced)
%       Fig4 : Power Spectral Density (PSD) Comparison
%       Fig5 : Spectrograms (Annotated)
%       Fig6 : SegSNR Comparison per File (Bar Chart)
%       Fig7 : Noise Reduction vs Speech Distortion
%       Fig8 : Statistical Summary (Boxplot + Histogram)
%
%   - project_data.mat containing:
%       Processed signals and evaluation metrics
%       (SegSNR, MSE, noise reduction, distortion, filter parameters)

% METHOD OVERVIEW:
%   1. Executes full processing pipeline (loading → baseline → enhancement)
%   2. Selects a representative audio sample for detailed visualization
%   3. Designs high-pass FIR filter (cutoff = 100 Hz)
%   4. Generates time-domain, frequency-domain, and statistical plots
%   5. Saves all figures in both MATLAB (.fig) and image (.png) formats
%   6. Stores key variables and metrics in a MAT file for reproducibility

% NOTES:
%   - Uses exportgraphics() for high-resolution figure saving (300 DPI)
%   - Ensures directory creation and file overwrite safety
%   - Separates visualization outputs from results_table metrics
%   - Designed to meet CEP submission requirements

clear; close all; clc;

% =========================================================================
% STEP 0 — RUN PIPELINE (loads data, computes baseline, runs filter)
% =========================================================================

fprintf('=======================================================\n');
fprintf('  Running Full Pipeline...\n');
fprintf('=======================================================\n\n');

run("loadaudios_1.m")
run("SNR_PSEQ_6.m")
run("Filter_applied_7.m")

% =========================================================================
% STEP 1 — CREATE OUTPUT FOLDER using absolute path (fixes savefig bug)
% =========================================================================

figDir = fullfile(pwd, 'figures');

if ~exist(figDir, 'dir')
    [status, msg] = mkdir(figDir);
    if ~status
        error('Could not create figures folder: %s', msg);
    end
    fprintf('Created folder: %s\n\n', figDir);
else
    fprintf('Saving into existing folder: %s\n\n', figDir);
end

% =========================================================================
% SHARED SETUP
% =========================================================================

repIdx   = 1;          % representative sentence for single-file plots
numFiles = length(data);
Fs_ref   = data(repIdx).Fs;
order    = 256;
b_hp     = fir1(order, 100/(Fs_ref/2), 'high');

Lmin     = min([length(data(repIdx).clean), ...
                length(data(repIdx).noisy), ...
                length(data(repIdx).enhanced)]);
clean    = data(repIdx).clean(1:Lmin);
noisy    = data(repIdx).noisy(1:Lmin);
enhanced = data(repIdx).enhanced(1:Lmin);
Fs       = data(repIdx).Fs;
t        = (0:Lmin-1) / Fs;

% =========================================================================
% FIGURE 1 — Filter Frequency Response (Magnitude + Phase)
% =========================================================================

fprintf('[1/8] Filter Frequency Response...\n');

fig1 = figure('Name','Filter_FreqResponse','Visible','on');
freqz(b_hp, 1, 1024, Fs_ref);
sgtitle('High-Pass FIR Filter — Frequency Response (Cutoff = 100 Hz)');

fp = fullfile(figDir, 'Fig1_Filter_FrequencyResponse');
savefig(fig1, [fp '.fig']);
exportgraphics(fig1, [fp '.png'], 'Resolution', 300);
fprintf('  Saved: Fig1_Filter_FrequencyResponse.fig + .png\n');

% =========================================================================
% FIGURE 2 — Group Delay
% =========================================================================

fprintf('[2/8] Group Delay...\n');

fig2 = figure('Name','Filter_GroupDelay','Visible','on');
grpdelay(b_hp, 1, 1024, Fs_ref);
title('High-Pass FIR Filter — Group Delay');
xlabel('Frequency (Hz)'); ylabel('Group Delay (samples)');

fp = fullfile(figDir, 'Fig2_Filter_GroupDelay');
savefig(fig2, [fp '.fig']);
exportgraphics(fig2, [fp '.png'], 'Resolution', 300);
fprintf('  Saved: Fig2_Filter_GroupDelay.fig + .png\n');

% =========================================================================
% FIGURE 3 — Time-Domain Waveform Comparison
% =========================================================================

fprintf('[3/8] Time-Domain Waveforms...\n');

fig3 = figure('Name','Waveform_Comparison','Visible','on');
set(fig3, 'Position', [100 100 1000 700]);

subplot(3,1,1);
plot(t, clean, 'b', 'LineWidth', 0.8);
title(sprintf('Clean Speech — %s', data(repIdx).label));
xlabel('Time (s)'); ylabel('Amplitude'); grid on; ylim([-1.1 1.1]);

subplot(3,1,2);
plot(t, noisy, 'r', 'LineWidth', 0.8);
title(sprintf('Noisy Speech (Airport, 10 dB SNR) — %s', data(repIdx).label));
xlabel('Time (s)'); ylabel('Amplitude'); grid on; ylim([-1.1 1.1]);

subplot(3,1,3);
plot(t, enhanced, 'g', 'LineWidth', 0.8);
title(sprintf('Enhanced Speech — %s', data(repIdx).label));
xlabel('Time (s)'); ylabel('Amplitude'); grid on; ylim([-1.1 1.1]);

sgtitle('Time-Domain Waveform Comparison');

fp = fullfile(figDir, 'Fig3_TimeDomain_Waveforms');
savefig(fig3, [fp '.fig']);
exportgraphics(fig3, [fp '.png'], 'Resolution', 300);
fprintf('  Saved: Fig3_TimeDomain_Waveforms.fig + .png\n');

% =========================================================================
% FIGURE 4 — Power Spectral Density Overlay
% =========================================================================

fprintf('[4/8] Power Spectral Density Overlay...\n');

fig4 = figure('Name','PSD_Overlay','Visible','on');
set(fig4, 'Position', [100 100 900 500]);

[P_clean,    f] = pwelch(clean,    hamming(512), 256, 512, Fs);
[P_noisy,    ~] = pwelch(noisy,    hamming(512), 256, 512, Fs);
[P_enhanced, ~] = pwelch(enhanced, hamming(512), 256, 512, Fs);

plot(f, 10*log10(P_clean),    'b',   'LineWidth', 1.5, 'DisplayName', 'Clean');    hold on;
plot(f, 10*log10(P_noisy),    'r--', 'LineWidth', 1.5, 'DisplayName', 'Noisy');
plot(f, 10*log10(P_enhanced), 'g-.', 'LineWidth', 1.5, 'DisplayName', 'Enhanced');
xline(300,  'k:', 'LineWidth', 1, 'DisplayName', '300 Hz (speech band)');
xline(3400, 'k:', 'LineWidth', 1, 'DisplayName', '3400 Hz (speech band)');
xline(100,  'm:', 'LineWidth', 1, 'DisplayName', '100 Hz (HP cutoff)');

xlabel('Frequency (Hz)'); ylabel('Power/Frequency (dB/Hz)');
title(sprintf('Power Spectral Density Overlay — %s', data(repIdx).label));
legend('Location', 'best'); grid on; xlim([0 Fs/2]);

fp = fullfile(figDir, 'Fig4_PSD_Overlay');
savefig(fig4, [fp '.fig']);
exportgraphics(fig4, [fp '.png'], 'Resolution', 300);
fprintf('  Saved: Fig4_PSD_Overlay.fig + .png\n');

% =========================================================================
% FIGURE 5 — Annotated Spectrograms (Clean / Noisy / Enhanced)
% =========================================================================

fprintf('[5/8] Annotated Spectrograms...\n');

fig5 = figure('Name','Spectrograms','Visible','on');
set(fig5, 'Position', [100 100 1100 800]);

nfft = 512; winLen = 256; noverlap = 200;

subplot(3,1,1);
spectrogram(clean,    hamming(winLen), noverlap, nfft, Fs, 'yaxis');
title(sprintf('Clean Speech Spectrogram — %s', data(repIdx).label));
clim([-80 20]); colorbar;
text(0.02, 0.92, 'Speech formants clearly visible in 300-3400 Hz band', ...
    'Units','normalized','Color','w','FontSize',7,'BackgroundColor',[0 0 0 0.4]);

subplot(3,1,2);
spectrogram(noisy,    hamming(winLen), noverlap, nfft, Fs, 'yaxis');
title(sprintf('Noisy Speech Spectrogram (Airport, 10 dB SNR) — %s', data(repIdx).label));
clim([-80 20]); colorbar;
text(0.02, 0.92, 'Broadband airport noise visible across all frequencies', ...
    'Units','normalized','Color','w','FontSize',7,'BackgroundColor',[0 0 0 0.4]);

subplot(3,1,3);
spectrogram(enhanced, hamming(winLen), noverlap, nfft, Fs, 'yaxis');
title(sprintf('Enhanced Speech Spectrogram — %s', data(repIdx).label));
clim([-80 20]); colorbar;
text(0.02, 0.92, 'Low-freq noise reduced; speech formants preserved', ...
    'Units','normalized','Color','w','FontSize',7,'BackgroundColor',[0 0 0 0.4]);

sgtitle('Spectrogram Comparison: Clean | Noisy | Enhanced');

fp = fullfile(figDir, 'Fig5_Spectrograms_Annotated');
savefig(fig5, [fp '.fig']);
exportgraphics(fig5, [fp '.png'], 'Resolution', 300);
fprintf('  Saved: Fig5_Spectrograms_Annotated.fig + .png\n');

% =========================================================================
% FIGURE 6 — SegSNR Improvement Per File (Bar Chart)
% =========================================================================

fprintf('[6/8] SegSNR Bar Chart (all files)...\n');

baseline_arr = [data.segSNR_baseline];
enhanced_arr = [data.segSNR_enhanced];
improvement  = enhanced_arr - baseline_arr;

fig6 = figure('Name','SegSNR_PerFile','Visible','on');
set(fig6, 'Position', [100 100 1000 450]);

b_bar = bar(1:numFiles, [baseline_arr; enhanced_arr]', 0.7);
b_bar(1).FaceColor = [0.85 0.33 0.10];
b_bar(2).FaceColor = [0.18 0.55 0.34];
hold on;

for k = 1:numFiles
    text(k, max(baseline_arr(k), enhanced_arr(k)) + 0.3, ...
        sprintf('%+.1f', improvement(k)), ...
        'HorizontalAlignment','center', 'FontSize', 7, 'Color', 'k');
end

xticks(1:numFiles); xticklabels({data.label}); xtickangle(45);
ylabel('SegSNR (dB)'); xlabel('File');
title('Segmental SNR: Baseline vs Enhanced (per file)');
legend({'Baseline (Noisy)', 'Enhanced'}, 'Location', 'best');
grid on; grid minor;

fp = fullfile(figDir, 'Fig6_SegSNR_PerFile_Bar');
savefig(fig6, [fp '.fig']);
exportgraphics(fig6, [fp '.png'], 'Resolution', 300);
fprintf('  Saved: Fig6_SegSNR_PerFile_Bar.fig + .png\n');

% =========================================================================
% FIGURE 7 — Noise Reduction & Speech Distortion per File
% =========================================================================

fprintf('[7/8] Noise Reduction & Speech Distortion...\n');

noise_red   = zeros(numFiles, 1);
speech_dist = zeros(numFiles, 1);

for idx = 1:numFiles
    Lm = min([length(data(idx).clean), length(data(idx).noisy), length(data(idx).enhanced)]);
    c  = data(idx).clean(1:Lm);
    n  = data(idx).noisy(1:Lm);
    e  = data(idx).enhanced(1:Lm);
    noise_red(idx)   = 10*log10(var(n - c) / (var(e - c) + eps));
    speech_dist(idx) = 10*log10(mean((c - e).^2) / (mean(c.^2) + eps));
end

fig7 = figure('Name','NR_SD_PerFile','Visible','on');
set(fig7, 'Position', [100 100 1000 450]);

yyaxis left;
bar(1:numFiles, noise_red, 0.5, 'FaceColor', [0.20 0.60 0.86], 'FaceAlpha', 0.8);
ylabel('Noise Reduction (dB)');

yyaxis right;
plot(1:numFiles, speech_dist, 'r-o', 'LineWidth', 1.5, 'MarkerSize', 5);
yline(-10, 'r--', 'Target < -10 dB', 'LineWidth', 1);
ylabel('Speech Distortion (dB)');

xticks(1:numFiles); xticklabels({data.label}); xtickangle(45);
xlabel('File');
title('Noise Reduction (bars) vs Speech Distortion (line) per File');
legend({'Noise Reduction (dB)', 'Speech Distortion (dB)', 'Distortion Target'}, 'Location','best');
grid on;

fp = fullfile(figDir, 'Fig7_NoiseReduction_SpeechDistortion');
savefig(fig7, [fp '.fig']);
exportgraphics(fig7, [fp '.png'], 'Resolution', 300);
fprintf('  Saved: Fig7_NoiseReduction_SpeechDistortion.fig + .png\n');

% =========================================================================
% FIGURE 8 — Summary Statistics
% =========================================================================

fprintf('[8/8] Summary Statistics Distribution...\n');

fig8 = figure('Name','Summary_Statistics','Visible','on');
set(fig8, 'Position', [100 100 800 500]);

subplot(1,2,1);
boxplot([baseline_arr', enhanced_arr'], {'Baseline SegSNR', 'Enhanced SegSNR'});
ylabel('SegSNR (dB)');
title('SegSNR Distribution Across All Files');
grid on;

subplot(1,2,2);
histogram(improvement, 8, 'FaceColor', [0.18 0.55 0.34], 'EdgeColor', 'k');
xline(mean(improvement), 'r--', sprintf('Mean = %+.2f dB', mean(improvement)), ...
    'LineWidth', 2, 'LabelVerticalAlignment', 'bottom');
xlabel('\Delta SegSNR (dB)'); ylabel('Count');
title('Distribution of SegSNR Improvement');
grid on;

sgtitle('Summary Statistics — Speech Enhancement Performance');

fp = fullfile(figDir, 'Fig8_Summary_Statistics');
savefig(fig8, [fp '.fig']);
exportgraphics(fig8, [fp '.png'], 'Resolution', 300);
fprintf('  Saved: Fig8_Summary_Statistics.fig + .png\n');

% =========================================================================
% SAVE WORKSPACE DATA  (separate from Results_Table outputs)
% =========================================================================

fprintf('\nSaving project_data.mat...\n');

baseline_segSNR_all   = [data.segSNR_baseline]';
enhanced_segSNR_all   = [data.segSNR_enhanced]';
mse_all               = [data.mse]';
noise_reduction_all   = noise_red;
speech_distortion_all = speech_dist;
file_labels           = {data.label}';
filter_order          = order;
filter_b_coeff        = b_hp;
Fs_used               = Fs_ref;

save('project_data.mat', ...
    'data', ...
    'baseline_segSNR_all', ...
    'enhanced_segSNR_all', ...
    'mse_all', ...
    'noise_reduction_all', ...
    'speech_distortion_all', ...
    'file_labels', ...
    'filter_order', ...
    'filter_b_coeff', ...
    'Fs_used');

fprintf('  Saved: project_data.mat\n');

% =========================================================================
% FINAL SUMMARY
% =========================================================================

fprintf('\n=======================================================\n');
fprintf('  ALL FILES SAVED SUCCESSFULLY\n');
fprintf('=======================================================\n');
fprintf('  Figures folder : %s\n', figDir);
fprintf('  Fig 1  : Filter Frequency Response    (.fig + .png)\n');
fprintf('  Fig 2  : Group Delay                  (.fig + .png)\n');
fprintf('  Fig 3  : Time-Domain Waveforms         (.fig + .png)\n');
fprintf('  Fig 4  : PSD Overlay                   (.fig + .png)\n');
fprintf('  Fig 5  : Annotated Spectrograms        (.fig + .png)\n');
fprintf('  Fig 6  : SegSNR per File Bar Chart     (.fig + .png)\n');
fprintf('  Fig 7  : Noise Reduction / Distortion  (.fig + .png)\n');
fprintf('  Fig 8  : Summary Statistics            (.fig + .png)\n');
fprintf('  Data   : project_data.mat\n');
fprintf('=======================================================\n\n');
fprintf('Run Results_Table_9.m separately for the metrics table,\n');
fprintf('CSV and cep_results_10dB.mat.\n');